version: '3.8'

services:
  app:
    build: .
    container_name: mlm-mining-futures-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
    restart: unless-stopped